### ISSUE TITLE
Haplomerger deps not on PATH

### ISSUE THREAD

**Issue by makopyan** [pdimens/LepWrap#5]
The haplomerger perl scripts call the binaries in `software/LepAnchor/deps/ubuntu/` but they aren't on the PATH, so it fails. 

Solution Options:
1. Create install script that creates the conda environment and moves the binaries to the conda `bin/` directory
2. Track down the binaries in the perl scripts and make them relative paths (least friction)
3. Users manually perform `cp software/LepAnchor/deps/ubuntu* /path/to/conda/env/bin/`

**Comment by pdimens** [comment]
Hopefully fixed with last commit #573a259
