### ISSUE TITLE
Red tries to use any ".fa" file in the working directory

### ISSUE THREAD

**Issue by kate-stankiewicz** [pdimens/LepWrap#7]
After running LM3 + LA, it killed at the chain step. In the 9_Chain folder, logs indicate there are duplicates of sequences (error in HM.initiation.log was "Species ( repeatmasked ) has a duplicate seq name (hic_scaffold_1  ) !" ), so checking 8_Repeatmask, I see everything is indeed duplicated in Red's output:

$ zcat repeatmasked.fa.gz | grep ">" | wc -l
812

$ zcat repeatmasked.fa.gz | grep ">" | sort | uniq | wc -l
406

In my working directory I had two copies of the genome reference to test some things, genome1.fa and genome2.fa (one masked and one unmasked, but the same genome). Even though I had not put reference to the other genome .fa file in the config file for LepWrap, it's mere presence in the working directory seemed to somehow cause Red to find it? In the 8_Repeatmask, I see files for BOTH fasta files:

$ ls 8_Repeatmask/
genome1.cnd
genome1.rpt
genome1.scr
genome2.cnd
genome2.rpt
genom2.scr
Red.log
repeatmasked.fa.gz

Moving one of the genome.fa files outside the LepWrap working directory so that Red can't find it solved this issue entirely. So it seems more than one .fa file can't be present in the working directory for LepAnchor to run properly. If you didn't have any scaffolds with the same names across multiple fasta genome files, this issue might go undetected because it only produced an error because my two fasta files had the exact same scaffold names, trigging a "duplicated seq name" error. If you have more than one ref fasta in the working dir, may want to check the number of sequences in the output of 8_Repeatmask to make sure it is as expected and not a concatenation of all the ref genomes (rather than just the one you wanted to run)?

**Comment by pdimens** [comment]
I've tracked down the issue to how `Red` needs to be run, with the first argument being an input folder. When I have access to my personal computer this evening I'll explore if that first positional argument has any wiggle room.
https://github.com/pdimens/LepWrap/blob/a4d91260e33c35f164ea5ea77a8f16cb6a070fe1/rules/LepAnchor/mask_and_chain.smk#L21

**Comment by kate-stankiewicz** [comment]
That fixed the issue and two .fa files can now be in the LepWrap working directory without Red having any issues! Thanks!
